---
version: '3.6'

networks:
  management:
    driver: overlay
    ipam:
      driver: default
  sniffvlan:
    driver: overlay
    ipam:
      driver: default
      
volumes:
  mongodb:
  syslog-ng:
  redis:
  sphinxsearch:
  snort:
  suricata:
  bro:

x-logging:
  &default-logging
    driver: syslog
    options:
      syslog-address: "tcp://127.0.0.1:514"
      tag: "{{.Name}}/{{.ID}}"
      syslog-format: rfc3164

services:
  MongoDB:
    image: 127.0.0.1:5000/mongodb:$BUILD_NUMBER
    build:
      context: MongoDB
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-031
          - node.hostname==adh-032
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
          - mongodb
    hostname: mongodb
    user: mongod
    volumes:
      - mongodb:/var/lib/mongodb
    logging: *default-logging

  WFE:
    image: 127.0.0.1:5000/wfe:$BUILD_NUMBER
    build:
      context: WFE
      shm_size: '2G'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
          - wfe
    hostname: wfe
    ports:
      - 5001:5000
    depends_on:
      - Syslog-NG
      - MongoDB
    logging: *default-logging

  elasticsearch:
    image: 127.0.0.1:5000/elasticsearch:$BUILD_NUMBER
    build:
      context: Elasticsearch
      shm_size: '2G'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
          - elasticsearch
    hostname: elasticsearch
    user: elasticsearch
    depends_on:
      - Syslog-NG
      - MongoDB
    logging: *default-logging

  Snort:
    image: 127.0.0.1:5000/snort:$BUILD_NUMBER
    build:
      context: Snort
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-030
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      sniffvlan:
        aliases:
          - snort
    hostname: snort
    volumes:
      - bro:/var/log/bro
      - snort:/var/log/snort
    depends_on:
      - Syslog-NG
    logging: *default-logging

  Suricata:
    image: 127.0.0.1:5000/suricata:$BUILD_NUMBER
    build:
      context: Suricata
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-030
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      sniffvlan:
        aliases:
          - suricata
    hostname: suricata
    volumes:
      - suricata:/var/log/suricata
    depends_on:
      - Syslog-NG
    logging: *default-logging

  nTop-NG:
    image: 127.0.0.1:5000/ntop-ng:$BUILD_NUMBER
    build:
      context: nTop-NG/nTop
      shm_size: '2G'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      sniffvlan:
        aliases:
          - ntopng
      management:
        aliases:
          - ntopng
    hostname: ntopng
    ports:
      - 3443:3443
    depends_on:
      - Syslog-NG
      - Redis
    logging: *default-logging

  nProbe:
    image: 127.0.0.1:5000/nprobe:$BUILD_NUMBER
    build:
      context: nTop-NG/nProbe
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-030
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
            - nprobe
      sniffvlan:
        aliases:
          - nprobe
    ports:
      - 2055:2055/udp
    hostname: nprobe
    depends_on:
      - Syslog-NG
      - MongoDB
    logging: *default-logging

  Redis:
    user: redis
    image: 127.0.0.1:5000/redis:$BUILD_NUMBER
    build:
      context: nTop-NG/Redis
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-031
          - node.hostname==adh-032
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
          - redis
    hostname: redis
    depends_on:
      - Syslog-NG
    logging: *default-logging

  Syslog-NG:
    image: 127.0.0.1:5000/syslog-ng:$BUILD_NUMBER
    build:
      context: Syslog-NG
      shm_size: '2G'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      management:
        aliases:
          - syslog
    hostname: syslog
    depends_on:
      - MongoDB
    volumes:
      - syslog-ng:/mnt/
      - bro:/var/log/bro:ro
    ports:
      - 514:514/tcp

  Bro:
    image: 127.0.0.1:5000/bro:$BUILD_NUMBER
    build:
      context: Bro
      shm_size: '2G'
    deploy:
      placement:
        constraints:
          - node.hostname==adh-030
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      sniffvlan:
        aliases:
          - bro
      management:
        aliases:
          - bro
    hostname: bro
    cap_add:
      - NET_ADMIN
    volumes:
      - bro:/opt/bro/logs/current
    depends_on:
      - Syslog-NG
    logging: *default-logging